// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCMjlVRpmBLqJfsnSM-Rv8fGOCrFA09co',
    appId: '1:1053922513156:web:35b0d60fbb5e9b34b48051',
    messagingSenderId: '1053922513156',
    projectId: 'farmtastic-7b5c3',
    authDomain: 'farmtastic-7b5c3.firebaseapp.com',
    storageBucket: 'farmtastic-7b5c3.appspot.com',
    measurementId: 'G-Z6G68E7P6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4AifZW23xfd1lXCsnl3TYgwmVTf2W_rk',
    appId: '1:1053922513156:android:b30ee9c2e0e79536b48051',
    messagingSenderId: '1053922513156',
    projectId: 'farmtastic-7b5c3',
    storageBucket: 'farmtastic-7b5c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDub-I_CN_uSamm0Ax761KfGfCeJiRpgII',
    appId: '1:1053922513156:ios:68aa05b0b5a09d54b48051',
    messagingSenderId: '1053922513156',
    projectId: 'farmtastic-7b5c3',
    storageBucket: 'farmtastic-7b5c3.appspot.com',
    androidClientId: '1053922513156-ol7m7d7gcjms8iumspe25hiameafsq6i.apps.googleusercontent.com',
    iosClientId: '1053922513156-g9fssbfkru1f9vsivfibhcgvtn5461ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmtastic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDub-I_CN_uSamm0Ax761KfGfCeJiRpgII',
    appId: '1:1053922513156:ios:8ea9e6583e5a8147b48051',
    messagingSenderId: '1053922513156',
    projectId: 'farmtastic-7b5c3',
    storageBucket: 'farmtastic-7b5c3.appspot.com',
    androidClientId: '1053922513156-ol7m7d7gcjms8iumspe25hiameafsq6i.apps.googleusercontent.com',
    iosClientId: '1053922513156-l2f8bclcmhad9mtak6dshe7pl3hhdmkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmtastic.RunnerTests',
  );
}
